version: 2
jobs:
  echo:
    macos:
      xcode: 11.3.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle --clean
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: pre-start simurator
          command: |
            udid=$(xcrun simctl list --json | jq -r '.devices["com.apple.CoreSimulator.SimRuntime.iOS-13-3"][] | select(.name == "iPhone 11") | .udid')
            xcrun simctl boot $udid
      - run:
          name: check simurator booted
          command: |
            xcrun simctl list --json | jq '.devices["com.apple.CoreSimulator.SimRuntime.iOS-13-3"][] | select(.name == "iPhone 11")'
      - run:
          name: Pre Build
          command: |
            bundle exec fastlane pre_build_app
      - run:
          name: install App to the booted simurator
          command: |
            xcrun simctl install booted simulator_build/Build/Products/Debug-iphonesimulator/Game.app
      - run:
          name: take snapshot
          command: |
            xcrun simctl launch booted com.circleci.ios-game
            xcrun simctl io booted screenshot screen.png
workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - echo
