fastlane_version "2.158.0"

default_platform :ios

platform :ios do
#  before_all do
#    setup_circle_ci
#  end
  desc "pre build"
  lane :pre_build_app do
     gym(
      scheme: 'Game',
      skip_package_ipa: true,
      skip_archive: true,
      destination: "platform=iOS Simulator,name=iPhone 11,OS=13.3",
      configuration: "Debug",
      derived_data_path: "simulator_build"
     )
  end

  desc "Runs all the tests"
  lane :test do
    scan
    snapshot
  end

  desc "Development build"
  lane :development do
    match(
      type: "development"
      # readonly: false
    )
    gym(
      scheme: 'Game',
      configuration: "Release",
      export_method: "development"
    )
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(
      scheme: 'Game',
      configuration: "Release",
      export_method: "ad-hoc"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(export_method: "app-store")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end
