default_platform :ios
MY_APP_ID = "com.circleci.ios-game"

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true
    )

    slather(
      proj: "Game.xcodeproj",
      scheme: "Game",
      source_directory: "../Game",
      cobertura_xml: true
    )

    snapshot
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(
      app_identifier: MY_APP_ID,
      type: "adhoc",
      git_url: 'git@github.com:ganezasan/circleci-demo-ios-certificates.git',
      readonly: true
    )
    gym(
      export_method: "ad-hoc",
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: {
          MY_APP_ID => "match AdHoc com.circleci.ios-game"
        }
      }
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(export_method: "app-store")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end
